<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_CountryMalaysia</name>
   <tag></tag>
   <elementGuidId>aa15cf00-1197-45f2-81c8-ab68b27218cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='contentBody']/div/app-static-layout/app-rate-calculator-v2/div/div[3]/div/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.country-container.shadow-md.rounded-lg.px-3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=/^CountryMalaysia$/ >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5ccb4221-e750-42ca-9de5-4bc701d99110</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>country-container shadow-md rounded-lg px-3</value>
      <webElementGuid>17aa8330-3112-4cd5-be7a-e2da1c829845</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CountryMalaysia</value>
      <webElementGuid>0d44a457-b5e5-4fae-b532-28f5aa9ded83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contentBody&quot;)/div[@class=&quot;content-bg min-h-full&quot;]/app-static-layout[1]/app-rate-calculator-v2[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;pt-2 sm:mt-24 mx-auto&quot;]/div[@class=&quot;calculator-wrapper w-full bg-[#F2EBFF] py-12&quot;]/div[@class=&quot;d-md-flex d-sm-block calculator-container max-w-7xl mx-auto mt-12 sm:space-x-3 px-6 sm:px-0 ng-untouched ng-pristine ng-invalid&quot;]/div[@class=&quot;calculator-col col-sm-12 w-35&quot;]/div[@class=&quot;country-container shadow-md rounded-lg px-3&quot;]</value>
      <webElementGuid>4aaf79c6-383a-43de-84b6-bc9d916075b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contentBody']/div/app-static-layout/app-rate-calculator-v2/div/div[3]/div/div/div[2]</value>
      <webElementGuid>d3b63d3e-1ff2-4eb0-a966-898f2358dbc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='From'])[1]/following::div[1]</value>
      <webElementGuid>98567d09-55d2-4898-85ea-68ae770fb496</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shipping Rate Calculator'])[1]/following::div[5]</value>
      <webElementGuid>21587c65-07c4-4048-aabb-ccdcdd2cfde0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]</value>
      <webElementGuid>87d0f824-19c1-4138-b34a-8e4eb4786b63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'CountryMalaysia' or . = 'CountryMalaysia')]</value>
      <webElementGuid>b4e2f1d3-9432-4f8c-a654-44cafb834742</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
