<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Weight (kg)_form-control border-right_6a9a58</name>
   <tag></tag>
   <elementGuidId>fe7be1a6-06a2-4423-8326-d0b54bc70860</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='number'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.form-control.border-right-0.ng-untouched.ng-dirty.ng-valid</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;eg. 0.1kg&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fac8a99c-5a49-4cdd-bf62-235cecfb53ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>6af54e20-9307-4527-852f-4aaa1b51ab15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>eg. 0.1kg</value>
      <webElementGuid>05c21131-9221-4a1a-87a4-930e875376a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>eg. 0.1kg</value>
      <webElementGuid>d585a2e9-d63a-4ffe-800f-0a3f5508a505</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>basic-addon2</value>
      <webElementGuid>8d975e05-55fb-4938-a147-c2accf489f8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>itemWeight</value>
      <webElementGuid>3edd93a4-9702-4589-a348-ad4259249c5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control border-right-0 ng-untouched ng-dirty ng-valid</value>
      <webElementGuid>3dfe3863-ecf3-4624-9796-3c3dce0c2ed6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contentBody&quot;)/div[@class=&quot;content-bg min-h-full&quot;]/app-static-layout[1]/app-rate-calculator-v2[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;pt-2 sm:mt-24 mx-auto&quot;]/div[@class=&quot;calculator-wrapper w-full bg-[#F2EBFF] py-12&quot;]/div[@class=&quot;d-md-flex d-sm-block calculator-container max-w-7xl mx-auto mt-12 sm:space-x-3 px-6 sm:px-0 ng-dirty ng-touched ng-valid&quot;]/div[@class=&quot;calculator-col col-sm-12 w-35&quot;]/div[@class=&quot;flex flex-col&quot;]/div[@class=&quot;weightinputblock flex flex-col input-group&quot;]/div[@class=&quot;flex flex-row no-wrap&quot;]/input[@class=&quot;form-control border-right-0 ng-untouched ng-dirty ng-valid&quot;]</value>
      <webElementGuid>d7edb43b-227f-4b60-965c-42efd90aef13</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='number'])[2]</value>
      <webElementGuid>bba80bd8-7422-4525-b373-226dc7008e0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contentBody']/div/app-static-layout/app-rate-calculator-v2/div/div[3]/div/div[3]/div/div[2]/div/input</value>
      <webElementGuid>9955aa4e-20b0-46d6-92a0-c67629ae0266</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[3]/div/div[2]/div/input</value>
      <webElementGuid>ad91b542-e7c9-42f6-8f97-9f279f6676e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @placeholder = 'eg. 0.1kg']</value>
      <webElementGuid>5eb04e36-09f9-4cf9-bb80-806808222aff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
